In [1]:
import pandas as pd
import numpy as np


In [2]:

data = pd.read_csv('https://raw.githubusercontent.com/Hnmani/ML-DA-I/main/class_resources/data/Advertising.csv')
data = data[["TV","Radio","Newspaper","Sales"]]
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

# **Model 1**


---


This Model Uses ...

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
model1 = LinearRegression()

In [5]:
X = data[["TV"]]
Y = data[['Sales']]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3)

In [8]:
model1.fit(X_train,Y_train);

In [9]:
model1.coef_

array([[0.04926497]])

In [10]:
model1.intercept_

array([6.84973531])

In [11]:
from sklearn import metrics

In [12]:
X_test_predicted = model1.predict(X_test)
X_train_predicted = model1.predict(X_train)

In [13]:
model1_mse_test = metrics.mean_squared_error(X_test_predicted,Y_test)

In [14]:
model1_mse_train = metrics.mean_squared_error(X_train_predicted,Y_train)

Model 2



In [15]:
model2 = LinearRegression()

In [16]:
X = data[["Radio"]]
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3)

In [17]:
model2.fit(X_train,Y_train)

LinearRegression()

In [18]:
model2.coef_

array([[0.20364691]])

In [19]:
model2.intercept_

array([9.20490528])

In [21]:
X_test_predicted = model2.predict(X_test)
X_train_predicted = model2.predict(X_train)

model2_mse_test = metrics.mean_squared_error(X_test_predicted,Y_test)
model2_mse_train = metrics.mean_squared_error(X_train_predicted,Y_train)
print(model2_mse_test,model2_mse_train)

18.633393621110734 17.870089670612586


Model3

In [26]:
model3 = LinearRegression()
X = data[["Newspaper"]]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size= 0.3)
model3.fit(X_train,Y_train)

print(model3.coef_, model3.intercept_)
X_train_predicted = model3.predict(X_train)
X_test_predicted  = model3.predict(X_test)

model3_mse_test = metrics.mean_squared_error(X_test_predicted,Y_test)
model3_mse_train = metrics.mean_squared_error(X_train_predicted,Y_train)
print(model3_mse_train,model3_mse_test)

[[0.05332358]] [12.00126721]
24.449299677621106 29.04683212474392
